# Generated by Django 3.0.2 on 2020-02-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='pic')),
            ],
        ),
        migrations.CreateModel(
            name='Secondhand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Description', models.TextField()),
                ('Used_Details', models.TextField()),
                ('Image', models.ImageField(upload_to='pic')),
            ],
        ),
    ]
