# Generated by Django 3.0.2 on 2020-02-04 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_secondhand_userid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
        migrations.AlterModelTable(
            name='secondhand',
            table='Secondhand',
        ),
    ]
