# Generated by Django 3.0.2 on 2020-02-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20200204_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='secondhand',
            name='Description',
            field=models.TextField(blank=True),
        ),
    ]
