# Generated by Django 3.0.2 on 2020-02-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20200205_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Price',
            field=models.DecimalField(decimal_places=2, default='499', max_digits=7),
        ),
        migrations.AlterField(
            model_name='secondhand',
            name='Price',
            field=models.DecimalField(decimal_places=2, default='499', max_digits=7),
        ),
    ]
