# Generated by Django 3.0.2 on 2020-02-06 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0006_auto_20200205_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondhand',
            name='Used_Details',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='secondhand',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
