# Generated by Django 3.0.2 on 2020-02-08 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondtransaction',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
