# Generated by Django 3.0.2 on 2020-02-08 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_thirdtry'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdtry',
            name='CheckOut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thirdtry',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
