# Generated by Django 3.0.2 on 2020-02-08 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_auto_20200206_1221'),
        ('Transaction', '0004_auto_20200208_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdtry',
            name='ProductId',
        ),
        migrations.RemoveField(
            model_name='thirdtry',
            name='SProductId',
        ),
        migrations.RemoveField(
            model_name='thirdtry',
            name='UserId',
        ),
        migrations.AddField(
            model_name='transaction',
            name='SProductId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.Secondhand'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ProductId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.Products'),
        ),
        migrations.DeleteModel(
            name='SecondTransaction',
        ),
        migrations.DeleteModel(
            name='thirdtry',
        ),
    ]
